version: '3.9'
services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: always
        ports:
            - 1434:1433
        environment:
            - "ACCEPT_EULA=Y"
            - "SA_PASSWORD=Belajar1234"
        volumes:
            - "sqlserver:/var/opt/mssql"
        
volumes:
    sqlserver: {}